// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqJMpC1AhpE843j4hhl7Nstd8Ynj63TYQ',
    appId: '1:175824095542:web:23b6048241573931fccb97',
    messagingSenderId: '175824095542',
    projectId: 'homeauto-4c25b',
    authDomain: 'homeauto-4c25b.firebaseapp.com',
    databaseURL: 'https://homeauto-4c25b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeauto-4c25b.firebasestorage.app',
    measurementId: 'G-4S4D89GRFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLTQKUzS9nKvAfkJqYOi8I2mkcP_Rs4lY',
    appId: '1:175824095542:android:644f65aa387b2689fccb97',
    messagingSenderId: '175824095542',
    projectId: 'homeauto-4c25b',
    databaseURL: 'https://homeauto-4c25b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeauto-4c25b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtCCpWBjTyqNWdhOJYOOcRIFFMZ0DtLRc',
    appId: '1:175824095542:ios:941c1212e3c87127fccb97',
    messagingSenderId: '175824095542',
    projectId: 'homeauto-4c25b',
    databaseURL: 'https://homeauto-4c25b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeauto-4c25b.firebasestorage.app',
    iosBundleId: 'com.example.homeauto2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtCCpWBjTyqNWdhOJYOOcRIFFMZ0DtLRc',
    appId: '1:175824095542:ios:941c1212e3c87127fccb97',
    messagingSenderId: '175824095542',
    projectId: 'homeauto-4c25b',
    databaseURL: 'https://homeauto-4c25b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeauto-4c25b.firebasestorage.app',
    iosBundleId: 'com.example.homeauto2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqJMpC1AhpE843j4hhl7Nstd8Ynj63TYQ',
    appId: '1:175824095542:web:23b6048241573931fccb97',
    messagingSenderId: '175824095542',
    projectId: 'homeauto-4c25b',
    authDomain: 'homeauto-4c25b.firebaseapp.com',
    databaseURL: 'https://homeauto-4c25b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeauto-4c25b.firebasestorage.app',
    measurementId: 'G-4S4D89GRFX',
  );
}
